# @Author: Haupt Joshua <HauptJ>
# @Date:   02-Apr-2018
# @Email:  josh@hauptj.com
# @Filename: selinux.yml
# @Last modified by:   HauptJ
# @Last modified time: 02-Apr-2018

---
  # Tasks to configure SELinux for MariaDB

- name: Configure SELinux to start mysql on any port
  seboolean:
    name: mysql_connect_any
    state: true
    persistent: yes

# SELinux policies: https://mariadb.com/kb/en/library/what-to-do-if-mariadb-doesnt-start/

- name: set the SELinux policy for Mariadb data directory
  sefcontext:
    target: '/var/lib/mysql(/.*)?'
    setype: mysqld_db_t
    state: present
    reload: yes

- name: Reload SELinux connection for MariaDB data directory
  command: restorecon -Rv /var/lib/mysql

- name: set the SELinux policy for Mariadb log file
  sefcontext:
    target: '/var/log/mysql(/.*)?'
    setype: mysqld_log_t
    state: present
    reload: yes

- name: Reload SELinux connection for mysqld.log
  command: restorecon -v /var/log/mysqld.log
